### ISSUE TITLE
(No Agent object matching ID "AGENT_17") Transfer/Firing of Scientists causes a later crash

### ISSUE THREAD

**Issue by Clihelm** [OpenApoc/OpenApoc#1066]
Hello. Sorry for my english. Using translator. The game crashes with this message:

![2](https://user-images.githubusercontent.com/87769223/137281488-08725442-a86f-4e33-9810-d39e7ab6edda.png)
![3](https://user-images.githubusercontent.com/87769223/137281491-fd64d276-6215-47d7-91a7-0e47a9186a6f.png)
![4](https://user-images.githubusercontent.com/87769223/137281496-5b7d8fbe-9ac8-473b-807c-b6626f00bb74.png)
![1](https://user-images.githubusercontent.com/87769223/137281499-a651e91e-2b0b-413c-93e5-7377cb18d579.png)

The game crashes after a while. I cannot understand at what moment. At the end of the work on the timer at about 8:55. I have no idea what event the game crashes.

Here is the log and save
[log.txt](https://github.com/OpenApoc/OpenApoc/files/7344470/log.txt)
[save_Map 1.zip](https://github.com/OpenApoc/OpenApoc/files/7344487/save_Map.1.zip)

Thank you very much for supporting this project. I'm waiting for the release. Good luck guys.

**Comment by Quickmind01** [comment]
I had this happen at the end of my stream this past Sunday and I figured out what's going on. When you fire a scientist, but hire them at another base at the same time, the game considers that a transfer. However, the scientist count at that first base (where the scientist was fired from) still counts that scientist as an agent. But, there is now a slot available for an additional scientist, allowing you to go above the max limit for that facility. Eventually, the game doesn't like this and gives the above crash. It's really easy to replicate.

I have attached 2 saves. Medium Stream is prior to the bug happening. Go to Base 2, hire a Quantum Physicist, fire a QP, but then hire the one you fired at Base 1 before completing the transaction. Complete the transaction and then go to your lab at Base 2. You will see "10" on the AQL picture, but only 9 QPs actually there. When you place the new hire in the lab, it will go up to "11." Medium Stream 2 shows my Base 2 with 14 QPs, and the crash occurs shortly after playing. There's also something weird going on with my 3 hoverbikes which seem to be cause the game to be unable to go to Ultraspeed, and the recovery vehicles aren't working so when vehicles crash, they eventually blow up instead of getting recovered.
[saves.zip](https://github.com/OpenApoc/OpenApoc/files/7464375/saves.zip)

I will upload a video as soon as I can explaining this in detail. I actually found even more information that may help while I was recording.

**Comment by Quickmind01** [comment]
Here is the link. Please wait about 30 minutes for Youtube to finish processing it. https://youtu.be/_mmYXqqpLOQ

**Comment by Quickmind01** [comment]
Oh, I also have the latest EWM build from FilmBoy and the OpenAPOC Original Sound Track remix.

**Comment by FilmBoy84** [comment]
Thanks for the update and saves quickmind, i have been able to replicate things as you described

I believe this save also contains examples of #989 (Hoverbikes stuck) and #983 (The vehicle recovery missions not spawning from rescue stations)

Will continue testing over this week to see if there's a way to get the same crash across multiple new games and from different approaches to Transfer/Fire/Hire between bases
