### ISSUE TITLE
cult of sirius buildings are destroyed upon successful raid, destroying the vehicle and killing all xcom agents

### ISSUE THREAD

**Issue by naamaesa** [OpenApoc/OpenApoc#1099]
started new superhuman game latest downloadable version x64
my normal routine is raiding all six cultist buildings every week
after a successful raid, the building collapses
didn't destroy my agent vehicle, so whatever
proceed to raid next building, it collapses after raid too, this time deleting valkyrie and all agents who were raiding
please fix :)

**Comment by FilmBoy84** [comment]
This has been reported before and tends not to be a bug when checked - Please confirm the following - you have disabled the "_Successful Raid Collapses Building_" option under Options->More Options->Successful Raid Collapses Building

I suspect this OpenApoc feature, on by default, to stop an exploit in the Original Game where players could raid for money endlessly with little penalty, remains enabled on on your game

![image](https://user-images.githubusercontent.com/33913088/181390131-9f5bb188-9311-4196-8442-48fa778a53a0.png)
![image](https://user-images.githubusercontent.com/33913088/181390145-b1e94140-97b0-4a2f-8c5b-2fb2f6f220c0.png)
![image](https://user-images.githubusercontent.com/33913088/181390178-8b8bef94-3c97-4a39-8b69-6e0d03a7f1eb.png)

There are currently known issues with city buildings and repairing (see other issues here on the tracker) so it makes sense to disable this feature in a new game at present anyway

The risk of building collapse on vehicle is intentional - you have to time your escape according to the building structure when the collapse feature is enabled - some buildings will require you keep your craft inside the garage, others will require you leave immediately, or anywhere in between to escape. Look at the building you are raiding, and plan what you will do on mission end in advance.

Until you are able to confirm that this is indeed a bug I shall leave it as "Won't Fix" for now

I have argued a few times for the default to be as original game, but equally, I can see why it's currently not - it fixes an original game exploit. Maybe, in time, we'll get a better design and feature implementation for it :)

**Comment by naamaesa** [comment]
omg why would someone collapse a building after a raid, killing their own agents in the process?
it's impossible to time any escape because the building goes down the second the mission is over.
just a terrible mod.

thank you for your clarification! will surely disable this.
and I recommend disabling this by default because it's super inconvenient and stupid tbh.
we're raiding the thing, not launching retribution missiles on it with our own agents inside.

**Comment by FilmBoy84** [comment]
Because the city repair functionality is not complete yet, it's not working quite as intended. So i'd argue not terrible, just not complete...

OpenApoc is at Alpha state, you will encounter a great deal that is not right, missing, incomplete, or buggy

Destroying rival organisations' buildings, even in the original game, is an important strategy - it cost the parent organisation money to repair and if you destroy enough of their property, you can force their finances into the red and they will stop sending units to attack you (or defend themselves from other organisatons)

When it is finally complimented by original game repair and finance systems, this OpenApoc feature will make more sense - not only will it allow you to do massive damage to a parent organisation by placing explosives in the building as you leave from a successful mission, the impact of that will be as follows

1) X-COM cannot just raid again for profit - the building will have to be rebuilt enough to allow future raids - this stops the endless raid abuse of the original game
2) The parent organisation will take a more serious penalty for not protecting itself from raids
3) There will be massive diplomatic and score penalties (damage to the city) for X-COM

As I said in my previous post - it is quite possible to escape the building collapse with careful planning and assessment of the building - this is currently not really an issue except for those not familiar with the feature

As our intent is to mimic the original game functionality and, where possible extend it with _OPTIONAL_ extra features, collapsing a building on a raid will NEVER be a compulsory option so fear not

I highly recommend checking out the other things under More Options that OpenApoc changes as this will have a drastic impact on your OpenApoc experience
