### ISSUE TITLE
Starting Agents - It should not be possible for a starting agent with a Mind Bender to be an Android

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1110]
**Describe the bug**
Currently no checks are made for the starting agents to ensure that class/species limits are obeyed with regards to load-out on a new game. It is entirely possible for the agent equipped with a Mind Bender on game start to be an Android type agent with no psi-abilities who therefore cannot use such a device

**To Reproduce**
1. Start a new game on any difficulty
2. Head to equip your agents
3. See if an android has been given a Mind Bender (or any other psi device; e.g. the mind shield)
4. If no android on this game start has an mind bender, abandon and restart a new game until it does

**Expected behavior**
A check needs to occur to ensure that, when spawning agents that carry a Mind Bender or any other psi-skill related device are psi-capable and not of the Android, or any other none-psi type agent, that may be in the original game or added by mods

**Comment by RedRobin84** [comment]
Hi @FilmBoy84, looked into the code and the solution is quite difficult.
Agents are imported randomly from XML as a map, which shuffles them every time randomly. Equipment is imported as a list, which means its sorted and is assigned is same order (to random agent) on every new game start. 
Equipment is one object as a set of items. 
I Did not found a type of a soldier (human / hybrid / android), but i suppose `agent.canTrain() `method should do, because only androids are not trainable.
Anyway - browsing the code, I've found more issues - with this random agent / equipment initialization - hybrid / android agents should be available based on relation with Mutalnt Aliance and S.E.L.F. organizations. I.e. there shouldn't be hybrids / androids available at the beginning of the game, or very limitedly. (didn't test it in OG though...)
More at: https://www.ufopaedia.org/index.php/Agents_(Apocalypse)#Recruitment_Algorhythm_explained

But that is different story I would say - solution to your issue could be something like `if agent is hybrid -> assign him mind bender set (last in the list)` and corner case `if agent is android and he is gonna receive mind bender set, assign him different equipment (e.g. first in the list)`

**Comment by FilmBoy84** [comment]
Resolved in #1174

**Comment by FilmBoy84** [comment]
> 

Many thanks for looking into this

As the core problem is resolved by #1174 to match the original game, i should probably make a new issue that requests the ability to change starting agents type, the RNG chance and any ratios, to modding as it's a feature request more than a bug/problem
