### ISSUE TITLE
The city is slowly populated by "stuck" vehicles with full health that have not crashed

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1113]
It is noticeable that, over time, the city becomes populated with vehicles that are stuck with full health or have crashed and failed to be recovered (there are other issues on the tracker that deal with this latter instance)

In the save attached, there are a couple of Osiron cars in the city that remain with full HP unable to finish their mission and stuck on the roads...

Possible issues related to this are #484, #562, #968, #983, #989, #1008 for stuck vehicles or pathfinding and #1009 , #763 and #749 for other influencing factors such as destroyed tiles in the city that appear repaired but remain destroyed in pathfinding terms

**To Reproduce**
1. Load the existing savegame below
2. Find the two hostile osiron cars (small red circles on map)
3. The cars do not disappear, or are recovered, over time - they remain stuck, on full HP, and never calling for recovery
[save_20221027 Save 18 2x Stuck Osiron.zip](https://github.com/OpenApoc/OpenApoc/files/9889509/save_20221027.Save.18.2x.Stuck.Osiron.zip)

**Comment by kgd192** [comment]
From looking at memory during debug at least the one vehicle (Civilian Car 48) currently does not have any active missions therfore is just idling. Which script is supposed to create the follow-up mission for ai cars?

**Comment by Andy51** [comment]
I have chcked that with the latest release (20230704) the stuck Osiron cars are now being successfully evacuated by Construction Vehicles.

**Comment by FilmBoy84** [comment]
Many thanks for the check
It does indeed appear to be resolved
Closing
🍻

**Comment by TorqvaldRenovator** [comment]
@FilmBoy84 
I believe this problem is recurring. Below is my report of the problem which I am experiencing in a current build of the game, and which appears to match the bug described in this Issue. 

If I may, I recommend re-opening this Issue. 


**Desktop (please complete the following information):**
-  OS: Windows 10 • OpenApoc Version: The one released on 20260916 found here: https://github.com/OpenApoc/OpenApoc/releases/tag/20260916 
- List of Mod files in use: By default, “OpenApoc base game” was enabled, and “Crashing Vehicles” was disabled.

**Describe the bug**
Several non-X-Com vehicles are ‘crashed’ on the city map, yet do not have low health. Most (if not all) of the vehicles are playing the smoking animation despite not having low health and appearing crashed. 
These vehicles are not recovered even after many hours of in-game time pass.

**To Reproduce**
Steps to reproduce the behavior:
    1. In the Save File, the game should load near the center/NW of the map. There, near some Slums buildings, you should see several vehicles exhibiting the problem. Some notable vehicles include:
Valkyrie Interceptor 78, owned by Psyke.
Hawk Air Warrior 63, owned by Psyke.
Hawk Air Warrior 70, owned by Psyke.

There are other vehicles in a similar state in the same area, but the above three are notable and easily visible.

Just west of the X-Com base in the save, there is a Rescue Transport 76 at full health, but ‘stuck’ in what appears to be a crashed state. There is a Rescue Transport 77 flying around it, possibly trying to rescue it. After 7 hours of game time after the Save’s current time, Rescue Transport 76 gets ‘Destroyed’ according to the in-game log.

The Psyke vehicles are NOT destroyed, even after more than 24 in-game hours pass. 

**Expected behavior**
Only vehicles with very low health should crash. I believe that intended behavior for crashed vehicles belonging to an organization is that those crashed vehicles will be recovered by vehicles owned by that organization.

**Savegame**
[UnusualDamagedVehicles.zip](https://github.com/user-attachments/files/32590823/UnusualDamagedVehicles.zip)

**Screenshots**
<img width="1280" height="720" alt="Image" src="https://github.com/user-attachments/assets/4e29afc1-f90d-45be-90ae-c16eaf4ba1c2" />

**Additional context**
Severity: I worry that too many vehicles remaining in a crashed, unrecoverable state might eventually cause a slow-down in the game.

Note: I’m meaning to start a new game, and wait until another major crime war happens to see if the problem occurs again in a fresh save, and maybe gather some further clues. 

**Copy of your OpenApoc_settings.conf**
[settings.zip](https://github.com/user-attachments/files/32590918/settings.zip)
