### ISSUE TITLE
Unplayable.

### ISSUE THREAD

**Issue by ArcherZett** [OpenApoc/OpenApoc#1157]
- after any game action, a crash may occur. Unplayable - because game progress is lost.
- pathfinding works WORSE than in the original. Operatives trying to get through people and getting stuck, moving in circles, not seeing the difference between floors, and more, more, more...
- on tactical missions, ALL civilians are marked as enemies, they have a target icon and player having a constant spam messages in the logs about enemy detection. In addition, when operatives see a civilian, the operatives constantly stop.
- the option to view the achievements of operatives does not work at all - the button is pressed, but nothing happens
- equipment sets do not work. In general, I did not even understand how they work, if they are present at all.
- When buying and selling, when you click on the arrow, sometimes the number changes to 1, sometimes to 2.
- it happens that ONE alien attacks the base, but 5 times in a row and different aliens.
Excuse me, but in the current state it will be easier to play the original. I haven't found much difference other than a few options.

**Comment by FilmBoy84** [comment]
The game is currently alpha state, a lot of these (such as achievements) simply are not implemented yet

Please also ensure you are using a Steam ISO, a GOG CUE/BIN or a 1:1 sector precise image of the Original UK/EU CD-ROM

Can you please post savegames (or videos) of these crashes and what you did to create them? Or even a description of what they are? (checking they are not already on the tracker first)

The civilian issue is known #849 and #410 are already on the tracker

Equipment sets were NOT in the original game - they are an OpenApoc feature. You equip an agent how you wish, then press `CTRL-<Number>` this will assign the equipment layout an ID. You can then press that assigned number on any other agent and as long as you have the equipment, it'll equip it

The number issue with the sales screen (or anything else with scrolling of values) is known and dealt with by #1156 that's waiting to be merged

Alien movement logic is already as original, however, the relations and diplomacy system that drive it is incomplete with only a dumb placeholder in the game. It was very much possible to have multiple base attacks with only one or two aliens in the Original Game when the decision matrix is working, though it is MUCH rarer due to the more extensive relations and diplomacy mechanism

A lot of these problems are either known, thus closing this issue until specific problems can be provided with saves and means to replicate
