### ISSUE TITLE
Ship stuck in slow-motion

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#1310]
- OS: Windows 10 x64 2020H2
 - OpenApoc Version 20231225-3
 - No mods

During combat in the alien dimension, a retaliator was repeatedly stasis bombed and at one point, it came back but remained very slow. Stays that way upon reloading.

[save_G4 Retaliator Slo-Mo.zip](https://github.com/OpenApoc/OpenApoc/files/13799000/save_G4.Retaliator.Slo-Mo.zip)

[Log Settings.zip](https://github.com/OpenApoc/OpenApoc/files/13799001/Log.Settings.zip)

**Comment by FilmBoy84** [comment]
This does indeed appear to be a slow craft

* Loaded save
* Deselected group of vehicles - selecting only retaliator
* Allowed time to pass - slow craft
* Selected manual control and instructed retaliator to move to a new location, allowed time to pass - slow
* Checked to see the top speed of craft, it's reporting correctly with no missing modules

![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/7757f796-3d88-4f18-b2f7-b1aab8679362)
![image](https://github.com/OpenApoc/OpenApoc/assets/33913088/34590373-2b30-4a39-a624-9a7b02111cdb)

**Comment by Kurtsley** [comment]
Been looking at this, this isn't a stasis bomb issue it is the last example of a vehicle getting "stuck" in the cityscape. While the other version of "stuck" was fixed, ships can get stuck moving very slowly across the map forever.

Fortunately, it seems to be fixable. I added a debug command that sets the vehicle's current position to it's goal position. When it warps to the spot it wants to be, the vehicle snaps out of it and acts normally. Why exactly this works is something I'm still working on, but there are some clues. 

First, from what I see this only happens on the slowest speed. This explains why I never had ships get stuck like this in my testing. I simply never user the slowest speed when testing aerial battles. When I noticed this issue in a couple of Filmboy's videos, it was when the speed was set to slowest.

Second, it looks like it happens in the middle of a turn. I have a hunch that it happens when a vehicle selects a new target when it's current target is destroyed. I say this because I didn't see it happen when damage was disabled.

I'm going to continue testing this, but hopefully it should be fixed soon and the stuck vehicle issue can be eliminated forever.

**Comment by FilmBoy84** [comment]
PARTIAL FIX via debug command in #1489 leaving open until fully resolved

**Comment by FilmBoy84** [comment]
#1492 offers a stopgap fix until the section of code dealing with the turn speed mechanic is fixed

Let us know how it works for you @BeornTB

**Comment by kgd192** [comment]
Having done some research pathfinding isnt actually the issue rather the slowdown for turnining calculation. Current Idea is to calculate the slowdown via the angular-velocity rather then via the ticks. Currently gathering some data, because it will for sure needs to have a certain correction factor similar too the ticksToMove. #997 will pretty sure have an impact on that and the code might be revisited during the ticks per second issue fixing process.
