### ISSUE TITLE
Add the City Repair Options to the More Options setting screen

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#1319]
As reported in #1188 there are a number of issues getting the recently merged Incremental City Repair features on to the More Options Screen / Form

In addition to this, the relevant options and their values are not added to the configuration file along with the other options on first run / change. This needs to be implemented.

**Comment by ayrtondenner** [comment]
Checking the code, I see that the problem starts with both new options being read as bool, which is not the case:

https://github.com/OpenApoc/OpenApoc/blob/319676dc5ed5391731df2f72384a2ac0a902823c/framework/options.cpp#L437-L444

I tried to programmatically find a way to determine each options type based on their declaration, but since I couldn't do it, I created a list with int and float options to check when the default bool approach is not the right one:

```c++
	// By default, city options list treat all options as boolean values
	// But we have some exceptions with different value types that needs to be checked
	const std::list<UString> cityNotificationsIntList = {"MaxTileRepair"};
	const std::list<UString> cityNotificationsFloatList = {"SceneryRepairCostFactor"};

	// FIXME: Can this be optimized?
	for (auto &p : *citynotificationList)
	{
		const UString full_name = p.first + "." + p.second;

		const auto isOptionInt =
		    std::find(cityNotificationsIntList.begin(), cityNotificationsIntList.end(), p.second) !=
		    cityNotificationsIntList.end();

		if (isOptionInt)
		{
			continue;
		}

		const auto isOptionFloat =
		    std::find(cityNotificationsFloatList.begin(), cityNotificationsFloatList.end(),
		              p.second) != cityNotificationsFloatList.end();

		if (isOptionFloat)
		{
			continue;
		}

		auto checkBox = mksp<CheckBox>(fw().data->loadImage("BUTTON_CHECKBOX_TRUE"),
		                               fw().data->loadImage("BUTTON_CHECKBOX_FALSE"));
		checkBox->Size = {240, citylistControl->ItemSize};
		checkBox->setData(mksp<UString>(full_name));
		checkBox->setChecked(config().getBool(full_name));
		auto label = checkBox->createChild<Label>(tr(config().describe(p.first, p.second)), font);
		label->Size = {216, citylistControl->ItemSize};
		label->Location = {24, 0};
		label->ToolTipText = tr(config().describe(p.first, p.second));
		label->ToolTipFont = font;
		citylistControl->addItem(checkBox);
	}
```
https://github.com/ayrtondenner/OpenApoc/blob/84fc0db81e566c1ad37cb76d806d114b3b53c5e2/game/ui/general/moreoptions.cpp#L130-L169

If anyone has a better way to check it, let me know so I can update this section. But this is not a blocker, since it's already checking which options are bool and which are not - its just not the best way to do it.

Meanwhile, do we have a form for int and float options? I see that we have `"forms/checkbox.h"` for bool options already, but couldn't find one for numeric values.
