### ISSUE TITLE
During base defense mission no equipment or aliens are recovered

### ISSUE THREAD

**Issue by muton-commander** [OpenApoc/OpenApoc#1333]
Windows 10

During base defense mission no equipment or aliens are recovered. No Craft present at base. 

One Spitter and one egg in hangar. After mission no corpses or live aliens captured. Removed agent equipment is lost.

Base has store space and Alien containment

[save_Aliens and equipment not recover.zip](https://github.com/OpenApoc/OpenApoc/files/14172621/save_Aliens.and.equipment.not.recover.zip)
[build-id.zip](https://github.com/OpenApoc/OpenApoc/files/14172630/build-id.zip)

[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14172622/settings.zip)

**Comment by Kurtsley** [comment]
Base defense missions break the existing logic for post-battle looting and alien capture. If you have no vehicle in the building where the battle takes place, you can't recover aliens. It does not check if this is a base and has alien containment or storage capacity. The same would happen if you DID have a vehicle but no bio transport module. The game would ignore the live aliens because it believes you can't successfully transport them home. 

There is another issue where if your base has multiple vehicles, they will be loaded with loot at the end of a base defense mission and create multiple "Items have arrived" messages. This needs to be fixed as well. Nothing should be loaded onto vehicles at the end of a base defense mission.

I believe a check in the exitBattle function could fix most of these issues as that is where the list of player vehicles is created to haul the cargo (around line 3157 in battle.cpp).

**Comment by XCOM-HUB** [comment]
@Kurtsley Funny you mentioned this just two days ago. I first ran into this yesterday and wrote about it today #1422
