### ISSUE TITLE
When making a save file with the same name as one that already exists, rather than asking "overwrite save file yes/no?" the game sometimes creates a new file with random extra numbers 

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1347]
(Note: large parts of this mystery are resolved in the next comment)

With 146 save files in the folder (184 total files including github zips), I've started noticing that saves I've made have failed to appear in the save file folder, or they do appear with random numbers added to the end. A save called "before week end 2" disappeared, and a save that should have been called "after week end 2" ended up being called "after week end 21181" somehow. 

Footage of myself making these saves and the buggy save file:

https://youtu.be/3F5is1O6n0U?list=PLdWM6woGnOQfDw-LC_E_CtQs7I12fSUrr&t=2997
[save_after week end 21181.zip](https://github.com/OpenApoc/OpenApoc/files/14323496/save_after.week.end.21181.zip)

Here's the last save file I made:
[save_104.zip](https://github.com/OpenApoc/OpenApoc/files/14323604/save_104.zip)

Window 10 x64 22H2
OpenApoc version 0.0.930
no mods in use
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14323529/settings.zip)

**Comment by dethstryke01** [comment]
After starting with an empty save folder and the last save I made from the old folder (save 104), everything seemed to be normal until I accidentally made a save called "113" three times (each time I thought 112 was the last save because the game wasn't listing the most recent save file at the top, possibly because of windows folder sorting settings). Instead of asking me whether I wanted to overwrite save 113, it generated two extra save files with the same random numbers attached to the end. This issue happened when there were less than twenty save files in the save folder.

[save_113.zip](https://github.com/OpenApoc/OpenApoc/files/14335691/save_113.zip)
[save_1131028.zip](https://github.com/OpenApoc/OpenApoc/files/14335692/save_1131028.zip)
[save_11320454.zip](https://github.com/OpenApoc/OpenApoc/files/14335693/save_11320454.zip)

I rechecked the video footage to see if "save_after week end 21181" had somehow been made when I overwrote a save file with the same name and discovered that a I had made a save called "after week end 2" five days earlier, meaning that the buggy save file with extra numbers was also created when the game attempted to create a new save with the same name as one that already existed. 

I also discovered that a save with the same name as the one I thought had disappeared (after week end 2) does exist in the old save file folder with the same timestamp from five days earlier. I thought it had failed to appear because I had the folder sorted by "date modified," and so I was looking for saves made on the 18th rather than checking to see if any saves by the same name had been made earlier.  In that case the game apparently just didn't make a new file rather than creating a new one with extra numbers added at the end. 

After watching the footage again, I also saw that "end session 17" had failed to appear because I didn't hit enter after typing in the name of the file. This means that no saves that should have appeared failed to appear (except possibly a version of "save before week end 2" with extra numbers).

Here are the original saves from the 13th.
[save_before week end 2.zip](https://github.com/OpenApoc/OpenApoc/files/14335753/save_before.week.end.2.zip)
[save_after week end 2.zip](https://github.com/OpenApoc/OpenApoc/files/14335659/save_after.week.end.2.zip)

**Comment by Kurtsley** [comment]
This is the culprit, random numbers are added to the name until a unique name is found before 5 tries. Strange that the random numbers don't show up in the save list. Implementing the save override function for this may get complicated. In the meantime, would adding (1), (2), (3), etc... to the saves be a better option if they actually appear in the list?

https://github.com/OpenApoc/OpenApoc/blob/a016802d94aa916ab1a52c24760508feca1f7209/game/state/savemanager.cpp#L164-L179

**Comment by ayrtondenner** [comment]
I think I will approach this naming issue in the same way OpenXcom does, [you can check it here](https://github.com/OpenXcom/OpenXcom/blob/e2c5a1b45c33957ce7e206207c5fb752c1e79ae1/src/Menu/ListSaveState.cpp#L189-L195)

Basically, when a savegame with the same name is found, we will add an underline at the end of the filename and try again until no savegame with that name is found, and then the saving can happen. Of course it will raise an exception when trying to save a file with a reaaaally long name, like "mission-final-cydonia________________________.sav" - which is the same behavior in OpenXcom.

**Comment by ayrtondenner** [comment]
Well, it could be an alternative as well. But like I said, when playing OpenXcom, they just create the new savefile with name + "_.sav" in such case.

**Comment by ayrtondenner** [comment]
> Is there any reason that the game shouldn't just ask if you want to overwrite the existing save of the name is the same?

Now that I think of it, this solution of adding a new underline maybe it's not the most elegant one. I guess I will ask the user if it should overwrite exiting save.

**Comment by Kurtsley** [comment]
The problem now is that even though random numbers are added to the save file, the name ends up being the same in the save game list. Even adding unique names to the identical saves in the list would be better than what is happening now. The new save and overwrite save functions seem to be very strict in what they do and I was having issues getting them to work together. I think the openxcom approach would be a great first step. I think this would be a pretty uncommon issue so that solution might end up being permanent.

**Comment by ayrtondenner** [comment]
In OpenXcom, the save name displayed in the game it's the name the user wrote, not the file name itself.

So if the user save "test" in two files, they both are going to appear as "test" and "test" in the game.
But in the save folder they will be saved as "test.sav" and "test_.sav"

**Comment by Kurtsley** [comment]
Do other games handle duplicate saves like this? It seems strange not to change the actual displayed save name if duplicate.

**Comment by JonnyH** [comment]
I think there's couple of different things interacting:

1) New saves are being created when the user expected to overwrite a previous game of the same name
2) Somehow we're ending up with "different" saves that map to the same filename, is this something that should actually happen in game? Is it due to some poor special character handing where they're "different" but collapsing to the same filename?
3) When ending up with an existing filename (see 2 and decide if this should even be supported), appending rand() an arbitrary number of times may not be the "expected" way of doing things - maybe a sort-able incrementing number or similar is a better experience (or openxcom's "incrementing numbers of "_" appended)
4) If saves differ only by filename, do we need some way of differentiating them in the save/load screens? Again we probably need to decide if this is something we should even support, and how we got to that state in the first place.

**Comment by JonnyH** [comment]
I think much of the code expects all standard library functions (std::filesystem etc) to work with utf8, as that's what's used internally. But I don't think that is the case for all windows versions - I seem to remember it was only introduced as an app-level option in (an update of) windows10, and not sure we're even setting that correctly.


If it is caused by poor non-ascii filesystem path handing, we could:
1) Exclude people on old or non-updated versions of windows by just enforcing utf8 everywhere
2) Jump through hoops to interact with the weird works-for-some-charactersets UCS2 native win32 APIs (Like boost::nowide)
3) Just disallow non-ascii filesystem names, and cope with filenames not matching the save titles (though this might not be an option if people keep openapoc/username in paths with non-ascii characters anyway...)

**Comment by Kurtsley** [comment]
I'm all for switching to the openxcom way of appending underscores, it seems to make more sense than the current system. My vote would be to ask the user if the existing save should be overwritten if the save names match. This would eliminate many of these issues. Whether this is practical is another matter.

**Comment by FilmBoy84** [comment]
Seconded on asking to overwrite

IIRC this is what the OG does with it's fixed 10 save slots

We have the advantage of allowing more saves, but it should still ask on overwrite (same name)
