### ISSUE TITLE
Format credit label value

### ISSUE THREAD

**Issue by ayrtondenner** [OpenApoc/OpenApoc#1380]
Right now, credit labels are presented without being formatted:
![credit](https://github.com/OpenApoc/OpenApoc/assets/13112588/d9a58d00-44ee-4408-a8ea-24893cd1a518)

We could update the value to **$356.161** for better readability

**Comment by Kurtsley** [comment]
Could this be worked into the translation somehow? I know different parts of the world use different separators eg in US $356,161.

**Comment by JonnyH** [comment]
The "localization" stuff currently was really a proof of concept and known not to be particularly fit and likely significantly reworked. One thing would be the localized formatting of numbers.

I think going too deep before that rework may not be too useful.

**Comment by ayrtondenner** [comment]
> Could this be worked into the translation somehow? I know different parts of the world use different separators eg in US $356,161.

Yep, like English speakers usually format numbers with comma (eg $356,161) while in Portuguese we use points instead (eg $356.161)

**Comment by BeornTB** [comment]
Same difference in French, and it makes Excel sheet databases a hot mess

**Comment by JonnyH** [comment]
There's a fair chunk of localization things that we need to fix that just aren't supported by the current system, what I can remember off the top of my head

- Number formatting
- Pluralization differences
- Sentence order and structure (e.g. many places construct strings in a fixed order, which can be incorrect in different languages)
- How to translate strings from mods
- Extracting translation strings from Form files
- How to deal with "missing" characters - the current apoc font files have a rather limited set of hand-drawn characters, so currently would require a new font set if a new character is used in a translation. But we could have a "fallback", might look ugly but still readable would probably be the goal.

Fixing these requires a fair rework, which would likely come easier after the Big String Formatting change I keep talking about but never finishing :P

There's some "features" of i18n that I don't think will be changed for apoc, though, as the "game world" isn't localized - I probably should put it up for comment to make sure I'm not ignoring something big due to my immersion into the Anglosphere, but I don't expect to need:

- Currency formatting (it's "magic space bucks")
- Different calendars (The "lore" I think says it's based in Future Canada, and really long-term date differences aren't a big deal in the game)
- (Unicode encoding specific) Support for non-normalized strings - e.g. there can be multiple ways of constructing a modified/accented character, either a direct encoding of the already-accented-character, or a character followed by (maybe multiple) "accent" modifier. The second form won't work right with the current font system, and I don't think there's (many? Any?) languages that *require* this to be legible, but might put limits on the translated strings to avoid those situations.


So yeah, I'm not sure where I was going with this, but maybe I just wanted to say there are "known" missing features that are (slowly) being worked on. And I probably need feedback from native-level speakers of various languages to make sure I'm not missing something important from my lists above. Maybe there should be a "I18N Rework" mega-issue to keep track of all this sort of stuff?
