### ISSUE TITLE
Renaming and overwriting old save files in game will not rename the save file

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1387]
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: 0.0.991
 - No Mods

I can no longer overwrite new text on my old save files in game. You can create a new save file and the text will be saved, but it will not allow any more name changes after that. This wasn't a problem before.

PS: The save files you overwrite work as usual, it's just that you can't change the text/rename anymore.

**Comment by ayrtondenner** [comment]
Gonna test with an older version, maybe this is something that changed after my PR https://github.com/OpenApoc/OpenApoc/pull/1371 that updated the save system regarding to file name

**Comment by ayrtondenner** [comment]
Before any update on this matter, I was wondering when exactly we want to rename savefiles instead of overwriting them?

Update https://github.com/OpenApoc/OpenApoc/pull/1371 was done because before it, whenever the user tried to create a new savefile with an already existing name, it ended up creating a new save file with an existing name + random suffix. Right now, the game will check if the name already exists and asks if the user wants to overwrite the existing savefile in the following situations:

1. If the user selects the existing savefile and tries to save without changing its name
2. When the user types the name for a new savefile but ends up typing the same name as an already existing one

I want to have more info on that before writing any update.

**Comment by ayrtondenner** [comment]
Just tested with an older version to be sure that it was renaming a save file before, it was indeed the case. I'm thinking about updating it with the following logic:

1. If the user selects an older row from an existing savefile, ask if it should overwrite if; if yes, then delete the savefile with the older name and create a new one with the new name - effectively renaming it.
2. If the user clicks in the "new" row but writes the name of an existing savefile, ask if it can overwrite it; if yes, then save new file with the same name, overwriting it.

I guess this is the logic that makes more sense.
