### ISSUE TITLE
Base selection doesn't update properly when selecting another base via tab view

### ISSUE THREAD

**Issue by ayrtondenner** [OpenApoc/OpenApoc#1392]
**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - OpenApoc Version 0.0.994
 - Mods: None

**Describe the bug**
If you enter Base view, enter another view via tabs where you can change between bases (eg Alien Containment), then you select another base and come back to Base view, the base name and map location doesn't work properly. Selecting base again doesn't update.

**To Reproduce**
1. Go to Bases view with Base 1 selected
2. Select a tab view that allows you to change base selection, eg Alien Containment
3. Select Base 2
4. Click OK
5. Base selection will show Base 2, but with name and location at map (red square) for Base 1
6. Click to select Base 2
7. No change will happen
8. Only if you click in Base 1 and then click in Base 2 that all information will be updated properly

**Expected behavior**
After leaving tab view, Base 2 should be properly selected at base selection, base name and base map location.

**Savegame**
[save_Stream Test.zip](https://github.com/OpenApoc/OpenApoc/files/14841282/save_Stream.Test.zip)

**Video**
https://youtu.be/VeqxuS47yRc

**Comment by Kurtsley** [comment]
In the OG, if you select a different base from a different view like Alien Containment or Transactions screen, the original base will remain selected when you go back to the base screen. So if you have base 1 selected, you will always be returned to base 1 when exiting any other screen. I actually think this is the correct way to do it since what you do in another view doesn't necessarily mean you want to switch bases in all views. If I'm buying things for base 2, I may not actually want to switch away from my main base when exiting the transaction screen. I know this isn't exactly what this issue is about, but I've noticed that this issue has come up before. Now, the incorrect base will be shown when exiting another screen and nothing is highlighted. Should the original functionality be kept?
