### ISSUE TITLE
CTD on start

### ISSUE THREAD

**Issue by witchiewoman** [OpenApoc/OpenApoc#1504]
Game crashes on new install of openapoc,

windows 11
nvidia 4060
Intel I7 
32gb ram
all drivers up to date.

Using newest version of openapoc. Game crashes stock and also if i use the extended weapons mod, either way. As soon as I start game and unpause, the game CTDs within a minute or so. Zip save included.

[m1.zip](https://github.com/user-attachments/files/17709731/m1.zip)

**Comment by witchiewoman** [comment]
copy of settings here
[settings.zip](https://github.com/user-attachments/files/17710010/settings.zip)

**Comment by witchiewoman** [comment]
Here is the log
[Uploading log.zip…]()

**Comment by witchiewoman** [comment]
Here is the log
[log.zip](https://github.com/user-attachments/files/17711093/log.zip)

**Comment by FilmBoy84** [comment]
Many thanks witchiewoman 🍻 

Hopefully this issue is resolved by Kurtsley's recent PR #1501

When the artefacts for this build here are finished (will be a couple of hours), can you please try on a new game to see if it still crashes?

https://ci.appveyor.com/project/OpenApoc/openapoc/builds/50970412
