### ISSUE TITLE
Clicking ouside of list still interacts with controls in said list

### ISSUE THREAD

**Issue by Istrebitel** [OpenApoc/OpenApoc#155]
JonnyH, if you have a hint at how to solve this, I'll code it, provided you don't have time of course.

**Comment by Istrebitel** [comment]
I added this to list.cpp:

```
void ListBox::eventOccured(Event *e)
{
	// ListBox does not pass mousedown and mouseup events when out of bounds
	if ((e->type() != EVENT_MOUSE_DOWN && e->type() != EVENT_MOUSE_UP) || eventIsWithin(e))
	{
		Control::eventOccured(e);
	}
```
Is this correct?

**Comment by pmprog** [comment]
Ah, that's very interesting. Indeed because it's checking against the child control bounds before the listbox bounds to see if it should actually be checking those items.

Hmmm, I vaguely remember a similar problem when I originally wrote the ListBox control. The source code now doesn't look much like what I wrote back in the day.

However, rather than making your suggested change, which will only fix ListBox (this problem is actually systemic), what is probably a better fix is something like this:

```
bool Control::recursiveInsideControl(Point mouseLocation)
{
 bool result = true;
 if( mouseLocation >= resolvedLocation && mouseLocation <= resolvedLocation + Size )
 {
  if( this->parent == nullptr )
  {
   result = true;
  } else {
  if( !this->parent->visible || !this->parent->enabled )
  {
   return false;
  } else {
   result = this->parent->recursiveInsideControl(mouseLocation);
  }
	}
 } else {
  result = false;
 }
 return result;
}
```

Then at https://github.com/OpenApoc/OpenApoc/blob/master/forms/control.cpp#L86
`bool newInside = recursiveInsideControl(e->mouse().Location)`

This means it'll check if the mouse is inside the bounds of the control it's checking, but also the bounds of all parent controls, makes sure they're visible and active, and that the mouse is inside that too

**Comment by Istrebitel** [comment]
okay let this issue remain then so we can return to it when we have luxury of spare time

**Comment by JonnyH** [comment]
Yeah, it's probably worth making a "1.0" milestone for "future tasks" - then we can carve out tasks to closer milestones (e.g. 0.2) as and when we decide what we're working on next

**Comment by pmprog** [comment]
@Istrebitel : This _should_ be fixed now (at least as far as my limited testing proved). If you still find any problems, let me know
