### ISSUE TITLE
Cannot attack alien

### ISSUE THREAD

**Issue by kazgaroth011** [OpenApoc/OpenApoc#176]
In turn based mode. I cannot attack the spitter even though he's next to me (it says "blocked").

![openapoc](https://user-images.githubusercontent.com/21365802/31299229-b90f52cc-aaed-11e7-8372-1ddc316a1a95.png)

Otherwise the game runs fine, congratulations on progress :) Nice to use the CD after 20 years.

**Comment by Istrebitel** [comment]
What you are seeing ("Blocked") means that you cannot go to this tile. 
You can attack like in vanilla
Option one is by clicking your weapon, then weapon becomes highlighet and cursor itself changes to "Attack" cursor, and then clicking on the enemy (instead of "blocked" you will see TU cost to fire one shot)
Alternatively, clicking Shift will produce an "forced" attack, which will fire both your weapons at target (or first weapon in TB) under the cursor. This way you can fire without clicking your weapon.

Tell me if this resolved your issue.

**Comment by kazgaroth011** [comment]
Thanks, well I did another playtest and the issue did not happen again. If it does, I'll just reopen this issue again.
