### ISSUE TITLE
Last build dont launch OpenApoc

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#190]
Last build wich partial economics and interfaces dont launch OpenApoc
just open window there blinks many srings
then closed and nothing
also nothing writes in log file..

**Comment by Paddywhacker** [comment]
Confirmed crash with "Vehicle turbo bike 10 deadlocked..." on starting a new game.

**Comment by Istrebitel** [comment]
will put a  fix now

**Comment by Istrebitel** [comment]
basically there is a bug which is hard to track, happens once in like 100 times, and it's vehicle deadlocking in a loop of "assigned mission to go to - finished mission to go to - assigned ...." and I want the game to give this message and ask to send a log instead of just hanging up. But I messed up and it gives the message when deadlock IS NOT occuring LOL!

But when fix is released this message will pop up when a vehicle does deadlock and if you catch it please attach the logs here

**Comment by makus82** [comment]
strange but new build dont change any

**Comment by Paddywhacker** [comment]
Works for me, but old saves are broken, as we expect when the format is extended.

**Comment by makus82** [comment]
Oh i get it new build dont work beacose of old config file
so need delete from file strings that added by game
and all start fine
