### ISSUE TITLE
Fullscreen Bug - No Start

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#266]
Under Windows 7 Ultimate x64 and with the following code at the head of the config file, the game does not start. Nothing is written to the log file. Full config attached

[OpenApoc_settings.zip](https://github.com/OpenApoc/OpenApoc/files/1501422/OpenApoc_settings.zip)

[Framework.Screen]
Width=1920
Height=1080
Fullscreen=1​

**Comment by makus82** [comment]
Its beacose old settings in file
so just remove all after SkipIntro = 1

**Comment by FilmBoy84** [comment]
@makus82 Have done as suggested, game still refuses to run, nothing sent to log file...
Current config attached

[OpenApoc_settings.zip](https://github.com/OpenApoc/OpenApoc/files/1506975/OpenApoc_settings.zip)

**Comment by JonnyH** [comment]
Other things to try:

- Run it from a command line - errors and warnings are also output to the console, so if for whatever reason the log file failed to be opened it should still output there
- Make sure you're running it from somewhere your current user has write permissions
- Make sure you have a "portable.txt" file in the same place as the openapoc.exe - that will mean it ignores system global settings and uses the local folder instead (It doesn't matter what's in the file, it can be empty, it only checks if the file exists). You could try without, which would cause it to use settings stored in your user's AppData folder instead of the local directory, in case the settings loading/local folder stuff is failing in some way.

**Comment by FilmBoy84** [comment]
@JonnyH All done, here's a screenshot of the command line.
Appears to be caused by the Fullscreen argument being invalid (even though it's using the "1" argument listed as a viable choice)

![image](https://user-images.githubusercontent.com/33913088/33286057-3a6755b8-d3ac-11e7-9c7f-d29ed7ed7a5c.png)

**Comment by JonnyH** [comment]
Looking at your attached settings, it looks like whatever editor you used to modify it has mangled the settings.

It's setting the "Framework.Fullscreen" variable to the character '1', then followed by the 3 byte "U+200B ZERO WIDTH SPACE" character before the newline. I guess as it's "zero width" it's not easy to see in an editor :)

Not sure how this happened, but removing that should allow it to work.

**Comment by FilmBoy84** [comment]
@JonnyH Interesting, i'll give it a go.
Using Notepad++ as my text editor so somewhat surprised
Commands were copy and pasted from @makus82 's install instructions on the forums... May be worth checking his post there for that zero width character too.

**Comment by FilmBoy84** [comment]
EDIT: Yep deleting character fixed it. Another Agent 3 CTD on exit though (as per the appropriate issue raised on github)...
[openapoc_log.txt](https://github.com/OpenApoc/OpenApoc/files/1507455/openapoc_log.txt)

**Comment by FilmBoy84** [comment]
This issue can be closed if no-one objects.
The cause was a zero-length character copied and pasted from the forums

**Comment by FilmBoy84** [comment]
_**The cause was a zero-length character copied and pasted from the forums**_

This is still a problem, but Makus/Ankor is already working to fix the places where the offending invisible character is

SupSuper and JonnyH have suggested other means and placements for the option to be changed in the future
