### ISSUE TITLE
[Linux] No any text in load/setting/buy/sell menu

### ISSUE THREAD

**Issue by DisDis** [OpenApoc/OpenApoc#421]
after https://github.com/OpenApoc/OpenApoc/issues/414
No any text in load/setting/buy/sell menu
![image](https://user-images.githubusercontent.com/87201/47315357-06d13580-d64d-11e8-874c-10b903c5b549.png)
![image](https://user-images.githubusercontent.com/87201/47315500-6deeea00-d64d-11e8-8829-52af694129e8.png)

**Comment by JonnyH** [comment]
This is likely due to the fonts not (Yet) containing the required characters for the translation - this problem will exist for all languages that have new characters that weren't supported by the original game (and in fact that was missing some variations, like capitals, of some characters too).

This isn't really a "bug", so much as these new translations are an incomplete feature of openapoc for now.

You should be able to try different languages by setting it in the config file - see here: https://www.ufopaedia.org/index.php/Installing_(OpenApoc)

The only one I /know/ that is complete is english, as it's the language I happen to use.

**Comment by DisDis** [comment]
It is not work.
```
[Framework]
Language=en_GB.UTF-8
```
![image](https://user-images.githubusercontent.com/87201/47316377-a8f21d00-d64f-11e8-930a-8ffb317b14ed.png)
@JonnyH ^^^

**Comment by JonnyH** [comment]
Huh, interesting. I'll have to look into it further.

**Comment by JonnyH** [comment]
This bisected back to 73f3a28ff6103dd51d4a74ccc3a80f98ed030bb0

Assuming that's correct, that's a GLM update - maybe a transform we were using now behaves differently?

**Comment by DisDis** [comment]
@JonnyH what will i can try?

**Comment by JonnyH** [comment]
^^ You can try that build when it finishes

**Comment by DisDis** [comment]
"master" works
