### ISSUE TITLE
On macOS, moving the mouse stops intro movie

### ISSUE THREAD

**Issue by ashenomo** [OpenApoc/OpenApoc#566]
I assume the expected behavior is to stop the intro movie when hitting Esc or maybe clicking the mouse, but not by just moving the mouse.

Hitting Esc also stops the movie.

**Comment by JonnyH** [comment]
This seems to be due to MacOS sending finger down/up events from touchpads - and due to mobile we see "finger down" as a reason to skip the intro movie.

I don't really know how to fix this - I might just disable all touchscreen support, as it's unlikely that chasing mobile support would give a good experience without a /large/ UI and controls overhaul anyway...
