### ISSUE TITLE
Bugged savegames Overwrite

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#617]
When I try to save game while selecting already present slot, the keyboard cursor is started blink from the begin of string with savegame's name and enteredg text overlay existing. After press ENTER - nothing happens. And OVERWRITE "yes/no" message dialog doesn't shows.

**Comment by FilmBoy84** [comment]
What build are you running?
I cannot recreate this on OpenApoc-X64-v0.1-475-g16a9c33c

**Comment by FilmBoy84** [comment]
Ah no, ignore that, it appears to apply to old save games only
Hmmmm will look into this
Adding the "help wanted" tag as i do not fully understand what is going on

**Comment by FilmBoy84** [comment]
Not sure what happened in this, but broken in a recent update
So assigning @JonnyH as he knows more than me what's changed :D

**Comment by JonnyH** [comment]
Just reproduced this - it seems like some Control activation issue - clicking on the name of the saved game shows the problem above, but clicking elsewhere on the button works fine.

**Comment by JonnyH** [comment]
So the issue here is that the saved game name control is a Label, with an invisible TextEdit over the top that is only made visible when that row's button is pressed (with SaveMenu::beginEditing()) and filled with the expected save name contents to be modified.

But in this case that 'invisible' TextEdit is still handling events, so when it gets clicked it handles the event instead of passing it down to the parent button, so it starts editing it's (empty) contents instead of calling SaveMenu::beginEditing().
