### ISSUE TITLE
Mod idea for More Options: Customise capacity of Stores & Accomodation

### ISSUE THREAD

**Issue by Paddywhacker** [OpenApoc/OpenApoc#679]
The ability to change the capacity of stores and accommodation would be wicked.  Lab space, too, if that didn't break the interface.  I remember hacking this in vanilla, but that was a long time ago.

**Comment by makus82** [comment]
Like cheats? or like facility ability to have a little more space if necessary and there no more facility for now

**Comment by Paddywhacker** [comment]
Yes, like a cheat, but maybe there could be research that allows you to pack more people in.

**Comment by makus82** [comment]
https://github.com/OpenApoc/OpenApoc/blob/master/README_HOTKEYS.txt
Here in case meybe you dont know

Base screens Debug:
- [F10] 
  - On base view: finish all facilities
  - On research screen: mark project as requiring just 100 more points(basically complete project at next update if you have at least 2 people assigned)

**Comment by FilmBoy84** [comment]
You can already alter the statistics of capacities and the market

The market is dealt with in economy.xml if i recall correctly

There are other xml files for other objects/buildings

**Comment by JonnyH** [comment]
If this is asking for a mod to do this, then I think it's somewhat out of scope for openapoc itself. This sort of thing doesn't make sense to embed within openapoc - as then you fall into the trap of trying to stuff /everything/ in, or drawing some arbitrary line of what "mods" are shipped with openapoc and which are external.

If it's asking for the /tools/ for someone to make a mod to do this, then the ability for a mod to add new research items, new building types, or modify existing building types should already be available.

Much of the UI and specifics around mods is still a work in progress though, but that's the same for all mods rather than anything specific.
