### ISSUE TITLE
OpenApoc Error - Open Palette

### ISSUE THREAD

**Issue by Urkvart** [OpenApoc/OpenApoc#681]
class std::shared_ptr<class OpenApoc::Palette> __cdecl OpenApoc::DataImpl::loadPalette(const class OpenApoc::UString &): Failed to open palette "xcom3/ufodata/pal_06.dat"

**Comment by makus82** [comment]
so OpenApoc dont want to start or its crash?

**Comment by Urkvart** [comment]
start

**Comment by makus82** [comment]
you act like its the fewer words the better =]
what build you use?

**Comment by Urkvart** [comment]
OpenApoc-x64-v0.1-563-g6c0ce2e4

**Comment by Urkvart** [comment]
Now adress - OpenApoc\data\cd.iso\UFODATA\pal_06.dat

**Comment by JonnyH** [comment]
On all the CDs I've seen the UFODATA folder is inside the xcom3/ folder

Is this a modified iso? Or extracted removing the folder? Or a difference for different localised CDs?

**Comment by makus82** [comment]
![image](https://user-images.githubusercontent.com/11581207/62564908-67ed9100-b88e-11e9-90e1-1bb949f4af9f.png)

**Comment by Urkvart** [comment]
Download GOG-Version...

**Comment by makus82** [comment]
you at discord? there info about use GOG version

**Comment by makus82** [comment]
and discord have web version 
so you no need install anything

**Comment by FilmBoy84** [comment]
This appears to be a user error

I can replicate if i EXTRACT a disc image and put that in the data folder instead of putting the ISO/BIN/CUE in as instructed below

Please bear in mind we also have an installer (although it needs a minor update for bin/cue)

`Simple` steps to play OpenApoc on Windows right now
(Keep in mind that it is ALPHA - this means bugs, crushes and not all features implemented)

1) Acquire X-Com Apocalypse original game CD, or an image/archive of that.
- you need have all files in ISO file including MUSIC etc
- if it's in .iso format, rename it to "cd.iso"
- if it's not, copy all the contents into a folder and rename the folder to "cd.iso"

2) Download: visit  https://ci.appveyor.com/project/openapoc/openapoc/
- If you see a green latest build then you can get it, if it's not then go to HISTORY at the top and click another build that's green
- Click Platform x64 (or Win32 if you need 32bit binaries)
- Click ARTIFACTS
- Download the first option (without "debug" in it)
- Unzip downloaded file which will create a new folder with everything from us inside

3) Put cd.iso (image or folder) into data folder inside OpenApoc folder
**- we also support the .cue / .bin files (which are used, for example, in the gog.com version)
- you rename the XCOM.cue file to "cd.iso", put it in the data/ folder, then put the XCOM.BIN
 file in the same folder
(without changing it's name - so for example the gog.com file remails "XCOM.BIN")**
Also you need openGl 2.0 video so its not launch at old laptops.

4) Run and enjoy!`

**Comment by Marsel24** [comment]
To solve this problem
Need
1) rename the file 'Xcom_3.iso' to 'MUSIC' and
2) drop it into the folder with the original game in the 'XCOM3' folder,
3) then drop this 'XCOM3' folder into the "data" folder 'OpenApoc'
4) register these paths in OpenApoc_Launcher.exe.
Earned and even the folder 'XCOM3' did not rename to cd.iso

**Comment by FilmBoy84** [comment]
It needs to be cd.iso and dropped in the OpenApoc data folder @Marsel24 

The cd.iso MUST also be an image of one of the official releases from Steam/GOG/UK-EU-CD-ROM and in the original release language (modified ISOs are not officially supported)

If this is not the case it can make bug-whacking very difficult for the devs when we don't know if it's the ISO used or OpenApoc itself causing problems
