### ISSUE TITLE
Craft Weapons Doubling up when using mods

### ISSUE THREAD

**Issue by FilmBoy84** [OpenApoc/OpenApoc#784]
When using mods that add a new version of the vehicle weapons XMLs, the game appears to specify both sets of weapons (even if identical) on the craft in cityscape

This leads to a doubling up of all weapons in combat with craft shooting twice the number of shots they would normally

It is also clear with a vehicle selected that there are two weapons instead of one in the screen below

The extra weapons do not show in the equip screen however

![image](https://user-images.githubusercontent.com/33913088/66704517-8059ac00-ed14-11e9-952a-5bcb7434c01a.png)

**Comment by FilmBoy84** [comment]
Hmmmm, on playing the EWM preview posted to PR #783 it also appears many things modified and therefore appearing in both the base mod xml and the ewm xml get duplicated

For example, a 3x UFO Type 2 and 2x UFO Type 1 invasion on week 1 becomes a 6x UFO Type 2 and 4x UFO Type 1 invasion

Not sure why the mod loading is happening in such a way as to duplicate values rather than replace them

**Comment by makus82** [comment]
when open skirmish at equipment screen its crash )

**Comment by emptyVoid** [comment]
> Not sure why the mod loading is happening in such a way as to duplicate values rather than replace them

It's due to the way the deserialization of `std::list` (and `std::vector`) is implemented -- any property represented as a list of entries will get the entries from mod added to the base entries.

https://github.com/OpenApoc/OpenApoc/blob/181a4fc46c92413f026af922a6ad291ac1585eb7/game/state/gamestate_serialize.h#L279-L312

One way to deal with this while not breaking existing functionality is to add an optional flag to the modded properties overriding default appending behavior, e.g. something like this:

```xml
<initial_equipment_list>
    <override>true</override>
    <entry>
        <first>
            <x>7</x>
            <y>1</y>
        </first>
        <second>VEQUIPMENTTYPE_RENDOR_PLASMA_GUN</second>
    </entry>
    <entry>
        <first>
            <x>4</x>
            <y>7</y>
        </first>
        <second>VEQUIPMENTTYPE_PROPHET_MISSILE_ARRAY</second>
    </entry>
    <entry>
        <first>
            <x>11</x>
            <y>7</y>
        </first>
        <second>VEQUIPMENTTYPE_JANITOR_MISSILE_ARRAY</second>
    </entry>
    <entry>
        <first>
            <x>6</x>
            <y>12</y>
        </first>
        <second>VEQUIPMENTTYPE_SD_ELITE</second>
    </entry>
</initial_equipment_list>
```

**Comment by FilmBoy84** [comment]
Good suggestion for a solution - I may look at that short-term

Though it would be preferred to have identical lines disregarded and only different lines overriding automatically on gamestate loading (according to their position in the mod-loader list)

How to do this is beyond my limited understanding though

**Comment by JonnyH** [comment]
Adding 'commands' to lists (e.g. 'append'/'delete') in the xml format has been on the todo list for a while - and is necessary for issues like this.

I'm generally leaning towards an attribute instead of a subnode, but I think the bikeshed should be painted mauve.

e.g. a 'op' attribute, only valid on lists/vectors/maps and map keys (though the last can be overridden, it's not currently possible to /remove/ them)

- For lists and vectors (as they're treated the same) the 'op' attribute can gave one of two values, 'append' and 'delete' - 'append' being the default. To replace a list, use 'delete' and then follow it with the new entries as normal.

e.g.
<my_list op="delete">
</my_list>

would remove all entries from my_list and:

<my_list op="delete">
<entry>1</entry>
</my_list>

would result in a list with a single entry - "1" - no matter how many entries were previously in the list.

No 'op' attribute would be treated as 'append' - which is the current behavior (any following entries are appended as new objects to the existing list)

- Maps would be 'override' and 'delete' - 'override' being the default, which would be the current behavior (e.g. add new or override if already matching key). 'delete' would replace the entire map with an empty map (removing all entries) before processing any following entries as normal.

e.g.
<my_map op="delete">
</my_map>

would result in an empty my_map

<my_map op="delete">
<entry>
<key>KEY1</key>
<value>VALUE1</value>
</entry>
</my_map>

would result in a map with a single entry with the key "KEY1" and "VALUE1"


- Map entries 'op' attribute can have one of the same values - 'override' and 'delete' - override being the default. Entries with a <key> with the op="delete" attribute but no value would be removed from the map, otherwise a new default <value> object would be created and populated as normal.

e.g.

<my_map>
<entry op="delete">
<key>KEY1</key>
</entry>
<my_map>

would remove a matching key of "KEY1" from the map - TODO: What happens if the key isn't found?

<my_map>
<entry op="delete">
<key>KEY1</key>
<value></value>
</entry>
<my_map>

would replace (or add) a matching key of "KEY1" from the map with a default constructed object - IE ALL it's members would return to default

<my_map>
<entry op="delete">
<key>KEY1</key>
<value>
  <child_value>3</child_value>
</value>
</entry>
<my_map>

would replace (or add) a matching key of "KEY1" from the map with a default constructed object then set "child_value" in it - IE ALL OTHER members would return to default


I think that fits all use cases?

**Comment by FilmBoy84** [comment]
That sounds like a reasonable solution

It would require me doing a lot of repetitive amendments to the EWM but only for the one version (and to be honest, that's exactly WHY i maintain the EWM so we have something to define a mod structure with and see what OpenApoc can do with new content)

From that point on new entries could be added with the appropriate attributes set as part of the process so i'm game if you are?

**Comment by JonnyH** [comment]
The default (IE none specified) should be the current behavior ('override' on maps and 'append' on lists/vectors) - so I think it should only require modifications for entries that you explicitly want to remove - such as the vehicle equipment lists in this bug.

Hopefully that means the changes shouldn't be huge? Or is this bug affecting lots of things currently?

**Comment by FilmBoy84** [comment]
It's affecting lots of things
Every craft weapon
The default load-out of every craft (both starting craft and new ones from the market)
And one instance where buying something from the market resulted in twice the amount of stuff delivered

I suppose my question regarding this method is as the only reason for adding vehicle related XML in the mod at the moment (It will change later) is to define the "burst" value for several weapons as well as make the civilian car purchaseable is would i have to change the mod to duplicate the entire orginal game XML within itself and "replace" or would simply listing the new attributes (and not the rest of the vehicle/weapon definition) suffice?

EWM v9p4 is linked above if you want to test on a build of my burst mode branch

**Comment by JonnyH** [comment]
If you don't op='delete' the entire map, all maps can be overrideable as today - e.g. just setting a single variable in each object requires you to just each entries key and only the new data in the value - all other values will remain as previously defined in that object.

Lists and vectors can't do this, as we have no way of knowing /which/ object you're changing, with no key to key off :)

**Comment by FilmBoy84** [comment]
This has been largely fixed by JonnyH's work
Closing
