### ISSUE TITLE
i cant edit vehicle equipment

### ISSUE THREAD

**Issue by psychokopr** [OpenApoc/OpenApoc#819]
when open vehicle sreen for editing wapons,def....is here a error text:

E class std::shared_ptr<class OpenApoc::Label> __cdecl OpenApoc::Control::findControlTyped<class OpenApoc::Label>(const class OpenApoc::UString &) const: Failed to find control "LABEL_4_%c" within form "VEHICLE_STATS_VIEW"
  0x0x13fad6a18 +0x%Ix

**Comment by JonnyH** [comment]
Is this a modified build? There isn't a "LABEL_4%c" in the "VEHICLE_STATS_VIEW" form?

Perhaps you're running with a data/ folder from a different openapoc version?

**Comment by psychokopr** [comment]
i downloaded version v.0.2.0.2-84 and i have only one,.... i have same problem with label1-10 in vehicles
[log.txt](https://github.com/OpenApoc/OpenApoc/files/4226260/log.txt)

**Comment by JonnyH** [comment]
Huh, it seems like you've downloaded a not-finished PR build rather than the latest master - try the one here: https://ci.appveyor.com/project/OpenApoc/openapoc/builds/30601674

It seems like appveyor doesn't distinguish as easily between master and PR builds - I'm sure it used to have a tab for branches etc. but can't find anymore

It seems the only way to see what is a master build is see if the entry on the "history" tab starts with a "Pull request #number" - less than user friendly :)

**Comment by psychokopr** [comment]
thx very much, now its working ;-)
