### ISSUE TITLE
[battlescape-rt] CTD when selecting agent on alien infiltration mission

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#823]
On mission start in real-time mode when I select next one of my agent on battlefield, game crashed with segmentation fault error.

![Screenshot from 2020-04-08 20-36-13](https://user-images.githubusercontent.com/37053399/78815613-2abb3f00-79d9-11ea-9656-48bb21740863.png)

[gdb_log.txt](https://github.com/OpenApoc/OpenApoc/files/4451966/gdb_log.txt)

**Comment by makus82** [comment]
А сейфгейм? было бы неплохо

**Comment by Atrosha** [comment]
Сейва нет, не успел сохранить.

**Comment by emptyVoid** [comment]
The log indicates crash happens on `createMotionInfo`, the issue was fixed in  #827.

**Comment by makus82** [comment]
hmm then if its fixed and u dont have save how you check it? @Atrosha 
pls check if its possible =P

**Comment by makus82** [comment]
i will check by @taehyoung1301 save

**Comment by makus82** [comment]
at latest build its crash game when i select agent 
[log.txt](https://github.com/OpenApoc/OpenApoc/files/4680825/log.txt)
[save_Good battle.zip](https://github.com/OpenApoc/OpenApoc/files/4680826/save_Good.battle.zip) with this save
@emptyVoid

**Comment by emptyVoid** [comment]
The fix doesn't work retroactively -- it clears the `in-use` flag at the end of battle, when transitioning to the cityscape; thus all the save games generated before the fix would have the flag set if player haven't deactivated motion scanners manually before battle ended.

Here's the relevant part from the attached save game:
```xml
<entry>
    <type>AEQUIPMENTTYPE_MOTION_SCANNER</type>
    <equippedPosition>
        <x>12</x>
        <y>6</y>
    </equippedPosition>
    <equippedSlotType>LeftHand</equippedSlotType>
    <ownerAgent>AGENT_1</ownerAgent>
    <ownerOrganisation>ORG_X-COM</ownerOrganisation>
    <armor>15</armor>
    <inUse>true</inUse>
</entry>
```

It would of course be great if we had a save game auto-patching utility, so that in case of retroactively applicable fixes it could patch save games on load.

**Comment by Atrosha** [comment]
In which file in savegame's archive does it has?

**Comment by emptyVoid** [comment]
`gamestate\agents.xml`
