### ISSUE TITLE
crash on click buttonsoldiers

### ISSUE THREAD

**Issue by helder1983** [OpenApoc/OpenApoc#882]
window closes when i click on recruit soldiers/enginners button.

using install-openapoc-v0.2.0.2-230-g4450e508.exe file

it happens in any dificulty.

[log.txt](https://github.com/OpenApoc/OpenApoc/files/4678563/log.txt)

**Comment by makus82** [comment]
thx for report @helder1983 ! ...

**Comment by makus82** [comment]
can cofirm but in my case its crash
and also by using reaserch button at same panel
[log.txt](https://github.com/OpenApoc/OpenApoc/files/4678599/log.txt)

**Comment by emptyVoid** [comment]
I can't seem to reproduce the issue using current **master**, any pointers would be appreciated.

**Comment by FilmBoy84** [comment]
Can't replicate either
Was it a tooltip crash i wonder? (Although the log does say button was clicked)
(Which emptyVoid has now fixed)

**Comment by emptyVoid** [comment]
It must have been something else -- tooltips didn't crash the game, they were just absent.

The curious part about this issue is that the installer's version `v0.2.0.2-230-g4450e508` implies it got built from sources 6 commits ahead of current **master**.
@helder1983 , are you a time traveler? 😆 

Seriously though, where does this installer come from? Might those additional commits (non-present in **master**) be involved in the crash?

**Comment by Atrosha** [comment]
It's may be a some PR's appveyor artifact.

**Comment by helder1983** [comment]
> It's may be a some PR's appveyor artifact.
> 
> this:
> https://ci.appveyor.com/project/OpenApoc/openapoc/builds/33089665/artifacts

@Atrosha sorry, was my mistake. you are right.
now i've downloaded from Current Build install-openapoc-v0.2.0.2-224-gd07d3ba6.exe, and it's working. thanks!

**Comment by FilmBoy84** [comment]
Excellent, thanks Atrosha
Closing
