### ISSUE TITLE
How about to update languages in OA?

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#908]
How about to update languages in OA?
So how better to do this?

**Comment by JonnyH** [comment]
This should be changing soon (and making it much easier) as a result of the work in PR #881 
Currently, there's no automated way of generating all the POT files (the translation templates), as there's a mix of xgettext being used in code (and even then many strings are split over format functions making it difficult to extract), and a mix of names being used in the game XML that aren't yet translated (though could be translated using a language "mod", but again there's no way of generating a template).

I currently see the translation scheme before #881 as a 'proof of concept' rather than a complete translation system.

Also, because of the format string changes that implies, it's probably not the best time to be starting new translation work, as the source strings *will* change significantly as a result of that, likely invalidating much of the work on the current example templates.

**Comment by makus82** [comment]
well then i update Russian and few others who have 100% by pull request (i want to see my changes in ru lang in the game)=]
and sorry i dont understand how its become easier to auto update files from transifex...
