### ISSUE TITLE
Logical problem with prices

### ISSUE THREAD

**Issue by makus82** [OpenApoc/OpenApoc#939]
I buy 3 types of grenade , bought everything, at first day
![image](https://user-images.githubusercontent.com/11581207/91424895-10d4a880-e863-11ea-8877-eff79acd72d9.png)

then wait week and new grenades delivered at market
but with half price and that not logical if buyer bought everything then 
you raise the price, but do not lower it by half...

![image](https://user-images.githubusercontent.com/11581207/91424598-b1769880-e862-11ea-84d0-1f5ab9cc0c4d.png)

**Comment by FilmBoy84** [comment]
Thanks for the report makus, this will come in useful as the economy is coded

Currently it's not fully implemented, so changed tag from "Enhancement" accordingly as this is something that needs to be done :)

**Comment by Istrebitel** [comment]
Wait wat? I implemented it according to wong's guide its in the :
EconomyInfo::update(GameState &state, bool xcom)

Ah.. its a simple bug

currentPrice = currentPrice * randBoundsInclusive(state.rng, 85, 5);

It should say 95 here, not 5. That's why it's halved, since it's actually reduced to 5% and then capped at 50%.

Wait wat... it should not apply this logic to megapol grenades, that logic is for alien and xcom equipment? For other equipment logic is properly implemented it looks like.

Okay so we have one bug there, and another . Just need to debug that (breakpoint at the economy update for megapol)and see how it gets that

**Comment by FilmBoy84** [comment]
This appears fixed by @Jarskih recently
Thanks for the help in resolving this issue @Istrebitel 
Closing
