### ISSUE TITLE
Crash when send vehicle to a site.

### ISSUE THREAD

**Issue by maximkotelnikov** [OpenApoc/OpenApoc#945]
1. RMB on the base
2. Select crew and move it to Valkyria interceptor1
3. Return to the map wiew, open vehicles tab, select Valkyria interceptor1
4. Press command "Go to building" and RMB on the Cult Of Sirius nearest building
5. Press "space" to release time and wait few seconds.

ER: Vehicle go to the building.
AR: Application crashes.

Video: https://drive.google.com/file/d/1gPietturCgiHNe4LHNWwXmAOoiiUGzWY/view?usp=sharing
Save: https://drive.google.com/file/d/1Q8k7c-Fc9_pIH6SlX1b0k3MK5CP8L-0R/view?usp=sharing

![1error](https://user-images.githubusercontent.com/6246363/95689491-cabc8400-0c19-11eb-8bbf-3e8a4e3c67ee.png)
![2error](https://user-images.githubusercontent.com/6246363/95689493-cbedb100-0c19-11eb-896c-2ba0a7dff435.png)
[error.txt](https://github.com/OpenApoc/OpenApoc/files/5361977/error.txt)

**Comment by maximkotelnikov** [comment]
Actualy do not need to do enything. Just release time and wait few secconds.
Previously I replaced weapons and engines for vihicles, hope it can helps.

**Comment by makus82** [comment]
Thx Maxim last few updates do game preatty buggy

**Comment by maitchison** [comment]
I have the same 'No vehicle object matching ID "VEHICLE_19" found' problem. Happens every time I load my save and press play.

**Comment by JonnyH** [comment]
I think I have a fix in pr #951 - though the "badness" has already happened in that save, so you'll probably need to start again (or if you have another save from a slightly earlier time)

Somehow we seem to have ended up with a vehicle that has been destroyed, yet still in the base's "currentVehicles" list.

As far as I can see, there's a couple of ways this might happen - the "Is this vehicle dead? If so then remove it from the building currentVehicles list" is right at the top of Vehicle::update() - so that means that if the vehicle is destroyed in it's own update() loop and in a building (e.g. as part of a Mission, such as the 'temporary ferry' OfferService mission, or as a result of another part of the update() loop after tis vehicle's update() has already been called) it'll hit that issue.

Was this just after a delivery or something arrived at the base? I think that's the most common cause of a temporary ferry?

**Comment by JonnyH** [comment]
I think this is fixed.

Feel free to create new issues as more missing IDs pop up :)
