### ISSUE TITLE
Fast forward is too SLOW...

### ISSUE THREAD

**Issue by endy2qq** [OpenApoc/OpenApoc#985]
[save_city22.zip](https://github.com/OpenApoc/OpenApoc/files/5938166/save_city22.zip)

Hello. 

Please check my save file 

Fast forward is too slow.

Thank you

**Comment by JonnyH** [comment]
Are you saying that the fast forward isn't working? Or the time step isn't correct according to the original?

Or are you just saying that it doesn't meet your performance expectations? IE fast-forward mode lags due to the extra calculations it does?

If it's the second, that's somewhat expected right now - we currently don't do as many "hacks" as the OG did for fast-forward mode (IE not bother to calculate paths etc.), so we end up doing a lot more work. And as this is still alpha still-massive-missing-features we haven't done any kind of performance optimisation pass, as there's no point trying to figure out how to make things faster when those things are going to change before 1.0 anyway.

Also, be aware that currently the vast majority of the game is currently processed in a single thread, which may cause slightly unexpected performance bottlenecks on "fast" hardware, as limitations in process technology have encouraged CPUs to go "wider" more than "faster" in the past decade or so, which we (Currently) don't take good advantage of.

This also means it can be very sensitive on software performance settings and turbo modes - e.g. if using a laptop make sure your power profile is setup to "performance" and it's plugged in - the power saving modes currently interact poorly with what we're doing.

And if it is a performance issue, listing the hardware you're running on would be very useful too - in case it's some hardware-specific bottleneck, some of which could be worked around.

**Comment by endy2qq** [comment]
Thank you very much

**Comment by endy2qq** [comment]
Thank you very much

**Comment by makus82** [comment]
You can btw get free simple reorder 
and record proccess for like 20 seconds
https://www.flashbackrecorder.com/express/

**Comment by endy2qq** [comment]
[test.zip](https://github.com/OpenApoc/OpenApoc/files/5943033/test.zip)
[save_city22.zip](https://github.com/OpenApoc/OpenApoc/files/5943037/save_city22.zip)

Thank you for your comment. 

Here is my save file and fbr file.

Please check. Thank you very much
